export const REQUEST_WEATHER = 'REQUEST_WEATHER'
export const RECIEVE_WEATHER = 'RECIEVE_WEATHER'
export const RECIEVE_WEATHER_ERROR = 'RECIEVE_WEATHER_ERROR'
export const RESOLVE_WEATHER_ERROR = 'RESOLVE_WEATHER_ERROR'
